{
 "title": "hbase metrics_monitoring",
 "tags": [
  "instance",
  "job",
  "name",
  "sub"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rs",
    "label": "rs",
    "query": "10.1.168.25,10.1.168.27,10.1.168.29,10.1.168.31,10.1.168.33,10.1.168.35,10.1.168.37,10.1.168.39"
   }
  ]
 },
 "panels": [
  {
   "title": "BlockCache  Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_blockCacheFreeSize",
     "legendFormat": "blockCacheFreeSize_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheSize",
     "legendFormat": "blockCacheSize_{{sub}}_{{instance}}"
    }
   ]
  },
  {
   "title": "Global BlockCache Hit rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_blockCacheCountHitPercent",
     "legendFormat": "blockCacheCountHitPercent_{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCache  Miss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_blockCacheCount", "legendFormat": "blockCacheCount_{{instance}}" },
    {
     "expr": "Hadoop_HBase_blockCacheMissCount",
     "legendFormat": "blockCacheMissCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheMissCountPrimary",
     "legendFormat": "blockCacheMissCountPrimary_{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCache  Evict",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_blockCacheCount", "legendFormat": "blockCacheCount_{{instance}}" },
    {
     "expr": "Hadoop_HBase_blockCacheEvictionCount",
     "legendFormat": "blockCacheEvictionCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheEvictionCountPrimary",
     "legendFormat": "blockCacheEvictionCountPrimary_{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCache Index/Data Hit Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_blockCacheDataHitCount",
     "legendFormat": "blockCacheDataHitCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheIntermediateIndexHitCount",
     "legendFormat": "blockCacheIntermediateIndexHitCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheRootIndexHitCount",
     "legendFormat": "blockCacheRootIndexHitCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheLeafIndexHitCount",
     "legendFormat": "blockCacheLeafIndexHitCount_{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCache Index/Data Miss Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_blockCacheDataMissCount",
     "legendFormat": "blockCacheDataMissCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheIntermediateIndexMissCount",
     "legendFormat": "blockCacheIntermediateIndexMissCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheRootIndexMissCount",
     "legendFormat": "blockCacheRootIndexMissCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheLeafIndexMissCount",
     "legendFormat": "blockCacheLeafIndexMissCount_{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCache Trailer/BloomChunk/FileInfo/Meta Hit  Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_blockCacheBloomChunkHitCount",
     "legendFormat": "BloomChunkHitCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheMetaHitCount",
     "legendFormat": "blockCacheMetaHitCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheTrailerHitCount",
     "legendFormat": "blockCacheTrailerHitCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheFileInfoHitCount",
     "legendFormat": "blockCacheFileInfoHitCount_{{instance}}"
    }
   ]
  },
  {
   "title": "BlockCache Trailer/BloomChunk/FileInfo/Meta Miss  Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_blockCacheBloomChunkMissCount",
     "legendFormat": "blockCacheBloomChunkMissCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheMetaMissCount",
     "legendFormat": "blockCacheMetaMissCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheTrailerMissCount",
     "legendFormat": "blockCacheTrailerMissCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_blockCacheFileInfoMissCount",
     "legendFormat": "blockCacheFileInfoMissCount_{{instance}}"
    }
   ]
  },
  {
   "title": "RT(queueCallTime+processCallTime)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_ProcessCallTime_min{instance=\"$rs:8080\"}",
     "legendFormat": "ProcessCallTime_min_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ProcessCallTime_max{instance=\"$rs:8080\"}",
     "legendFormat": "ProcessCallTime_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ProcessCallTime_mean{instance=\"$rs:8080\"}",
     "legendFormat": "ProcessCallTime_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ProcessCallTime_median{instance=\"$rs:8080\"}",
     "legendFormat": "ProcessCallTime_median_{{instance}"
    },
    {
     "expr": "Hadoop_HBase_QueueCallTime_min{instance=\"$rs:8080\"}",
     "legendFormat": "QueueCallTime_min_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_QueueCallTime_max{instance=\"$rs:8080\"}",
     "legendFormat": "QueueCallTime_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_QueueCallTime_mean{instance=\"$rs:8080\"}",
     "legendFormat": "QueueCallTime_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_QueueCallTime_median{instance=\"$rs:8080\"}",
     "legendFormat": "QueueCallTime_median_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_TotalCallTime_min{instance=\"$rs:8080\"}",
     "legendFormat": "TotalCallTime_min_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_TotalCallTime_max{instance=\"$rs:8080\"}",
     "legendFormat": "TotalCallTime_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_TotalCallTime_mean{instance=\"$rs:8080\"}",
     "legendFormat": "TotalCallTime_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_TotalCallTime_median{instance=\"$rs:8080\"}",
     "legendFormat": "TotalCallTime_median_{{instance}}"
    }
   ]
  },
  {
   "title": "Global QueueSize",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_queueSize", "legendFormat": "queueSize_{{instance}}" }
   ]
  },
  {
   "title": "Request/Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_RequestSize_min{instance=\"$rs:8080\"}",
     "legendFormat": "RequestSize_min_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_RequestSize_max{instance=\"$rs:8080\"}",
     "legendFormat": "RequestSize_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_RequestSize_mean{instance=\"$rs:8080\"}",
     "legendFormat": "RequestSize_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_RequestSize_median{instance=\"$rs:8080\"}",
     "legendFormat": "RequestSize_median_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ResponseSize_min{instance=\"$rs:8080\"}",
     "legendFormat": "ResponseSize_min_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ResponseSize_max{instance=\"$rs:8080\"}",
     "legendFormat": "ResponseSize_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ResponseSize_mean{instance=\"$rs:8080\"}",
     "legendFormat": "ResponseSize_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ResponseSize_median{instance=\"$rs:8080\"}",
     "legendFormat": "ResponseSize_median_{{instance}}"
    }
   ]
  },
  {
   "title": "MemStore",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_memStoreSize{instance=\"$rs:8080\"}",
     "legendFormat": "memStoreSize_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_DecreaseMemStoreSize_max{instance=\"$rs:8080\"}",
     "legendFormat": "DecreaseMemStoreSize_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_DecreaseMemStoreSize_mean{instance=\"$rs:8080\"}",
     "legendFormat": "DecreaseMemStoreSize_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_IncreaseMemStoreSize_max{instance=\"$rs:8080\"}",
     "legendFormat": "IncreaseMemStoreSize_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_IncreaseMemStoreSize_mean{instance=\"$rs:8080\"}",
     "legendFormat": "IncreaseMemStoreSize_mean_{{instance}}"
    }
   ]
  },
  {
   "title": "Mem Heap/NonHeap (MB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_MemMaxM{instance=\"$rs:8080\"}",
     "legendFormat": "MemMaxM_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MemHeapCommittedM{instance=\"$rs:8080\"}",
     "legendFormat": "MemHeapCommittedM_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MemHeapMaxM{instance=\"$rs:8080\"}",
     "legendFormat": "MemHeapMaxM_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MemHeapUsedM{instance=\"$rs:8080\"}",
     "legendFormat": "MemHeapUsedM_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MemNonHeapCommittedM{instance=\"$rs:8080\"}",
     "legendFormat": "MemNonHeapCommittedM_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MemNonHeapMaxM{instance=\"$rs:8080\"}",
     "legendFormat": "MemNonHeapMaxM_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MemNonHeapMaxM{instance=\"$rs:8080\"}",
     "legendFormat": "MemNonHeapMaxM_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MemNonHeapMaxM{instance=\"$rs:8080\"}",
     "legendFormat": "MemNonHeapMaxM_{{instance}}"
    }
   ]
  },
  {
   "title": "Minor compaction Blocked/Unblocked Flush num_ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_UnblockedFlushes_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "UnblockedFlushes_num_ops_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_BlockedFlushes_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "BlockedFlushes_num_ops_{{instance}}"
    }
   ]
  },
  {
   "title": "Minor compaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_flushedMemstoreBytes{instance=\"$rs:8080\"}",
     "legendFormat": "flushedMemstoreBytes_{{instance}}"
    }
   ]
  },
  {
   "title": "Minor compaction Blocked/Unblocked Flush  cost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_BlockedFlushes_max{instance=\"$rs:8080\"}",
     "legendFormat": "BlockedFlushes_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_BlockedFlushes_mean{instance=\"$rs:8080\"}",
     "legendFormat": "BlockedFlushes_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_UnblockedFlushes_max{instance=\"$rs:8080\"}",
     "legendFormat": "UnblockedFlushes_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_UnblockedFlushes_mean{instance=\"$rs:8080\"}",
     "legendFormat": "UnblockedFlushes_mean_{{instance}}"
    }
   ]
  },
  {
   "title": "Major compaction cost",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_MajorCompactionTime_max{instance=\"$rs:8080\"}",
     "legendFormat": "MajorCompactionTime_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_MajorCompactionTime_mean{instance=\"$rs:8080\"}",
     "legendFormat": "MajorCompactionTime_mean_{{instance}}"
    }
   ]
  },
  {
   "title": "Major compaction gauge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_majorCompactedCellsCount{instance=\"$rs:8080\"}",
     "legendFormat": "majorCompactedCellsCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CompactionInputFileCount_max{instance=\"$rs:8080\"}",
     "legendFormat": "CompactionInputFileCount_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CompactionOutputFileCount_max{instance=\"$rs:8080\"}",
     "legendFormat": "CompactionOutputFileCount_max_{{instance}}"
    }
   ]
  },
  {
   "title": "Major compaction in/out bound",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_majorCompactedCellsSize{instance=\"$rs:8080\"}",
     "legendFormat": "majorCompactedCellsSize_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_majorCompactedInputBytes{instance=\"$rs:8080\"}",
     "legendFormat": "majorCompactedInputBytes_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_majorCompactedOutputBytes{instance=\"$rs:8080\"}",
     "legendFormat": "majorCompactedOutputBytes_{{instance}}"
    }
   ]
  },
  {
   "title": "Workload  Thread Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount",
     "legendFormat": "ThreadCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_numActiveReadHandler",
     "legendFormat": "numActiveReadHandler_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_numActiveScanHandler",
     "legendFormat": "numActiveScanHandler_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_numActiveWriteHandler",
     "legendFormat": "numActiveWriteHandler_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_numActiveHandler{instance=\"$rs:8080\"}",
     "legendFormat": "numActiveHandler_{{instance}}"
    }
   ]
  },
  {
   "title": "Workload read/write RequestCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_queueSize", "legendFormat": "queueSize_{{instance}}" },
    { "expr": "Hadoop_HBase_readRequestCount", "legendFormat": "readRequestCount_{{instance}}" },
    { "expr": "Hadoop_HBase_writeRequestCount", "legendFormat": "writeRequestCount_{{instance}}" }
   ]
  },
  {
   "title": "Workload RPC Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_rpcScanRequestCount",
     "legendFormat": "rpcScanRequestCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_rpcGetRequestCount",
     "legendFormat": "rpcGetRequestCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_rpcMultiRequestCount",
     "legendFormat": "rpcMultiRequestCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_rpcMutateRequestCount",
     "legendFormat": "rpcMutateRequestCount_{{instance}}"
    }
   ]
  },
  {
   "title": "Workload Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_receivedBytes", "legendFormat": "receivedBytes_{{instance}}" },
    { "expr": "Hadoop_HBase_writtenBytes", "legendFormat": "writtenBytes_{{instance}}" }
   ]
  },
  {
   "title": "Scan Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_ScanSize_max", "legendFormat": "ScanSize_max_{{instance}}" },
    { "expr": "Hadoop_HBase_ScanSize_mean", "legendFormat": "ScanSize_mean_{{instance}}" }
   ]
  },
  {
   "title": "Scan num_ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_ScanTime_num_ops", "legendFormat": "ScanTime_num_ops_{{instance}}" }
   ]
  },
  {
   "title": "ScanTime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_ScanTime_mean", "legendFormat": "ScanTime_mean_{{instance}}" },
    { "expr": "Hadoop_HBase_ScanTime_max", "legendFormat": "ScanTime_max_{{instance}}" }
   ]
  },
  {
   "title": "RPC  Put/PutBatch/Get/GetScan RT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_Get_mean{instance=\"$rs:8080\"}",
     "legendFormat": "Get_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_Get_max{instance=\"$rs:8080\"}",
     "legendFormat": "Get_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_Put_mean{instance=\"$rs:8080\"}",
     "legendFormat": "Put_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_Put_max{instance=\"$rs:8080\"}",
     "legendFormat": "Put_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_PutBatch_mean{instance=\"$rs:8080\"}",
     "legendFormat": "PutBatch_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_PutBatch_max{instance=\"$rs:8080\"}",
     "legendFormat": "PutBatch_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ScanTime_mean{instance=\"$rs:8080\"}",
     "legendFormat": "Scan_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ScanTime_max{instance=\"$rs:8080\"}",
     "legendFormat": "Scan_max_{{instance}}"
    }
   ]
  },
  {
   "title": "RPC num_ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_Get_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "Get_num_ops_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_Put_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "Put_num_ops_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_PutBatch_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "PutBatch_num_ops_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_ScanTime_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "Scan_num_ops_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CheckAndPut_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "CheckAndPut_num_ops_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CheckAndDelete_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "CheckAndDelete_num_ops_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_Bulkload_num_ops{instance=\"$rs:8080\"}",
     "legendFormat": "Bulkload_num_ops_{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Bulkload/CheckAndPut/CheckAndDelete RT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_Bulkload_mean{instance=\"$rs:8080\"}",
     "legendFormat": "Bulkload_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_Bulkload_max{instance=\"$rs:8080\"}",
     "legendFormat": "Bulkload_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CheckAndPut_mean{instance=\"$rs:8080\"}",
     "legendFormat": "CheckAndPut_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CheckAndPut_max{instance=\"$rs:8080\"}",
     "legendFormat": "CheckAndPut_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CheckAndDelete_mean{instance=\"$rs:8080\"}",
     "legendFormat": "CheckAndDelete_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_CheckAndDelete_max{instance=\"$rs:8080\"}",
     "legendFormat": "CheckAndDelete_max_{{instance}}"
    }
   ]
  },
  {
   "title": "GC  Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_GcCount", "legendFormat": "GcCount_{{instance}}" },
    {
     "expr": "Hadoop_HBase_GcCountG1_Young_Generation",
     "legendFormat": "GcCountG1_Young_Generation_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_GcCountG1_Old_Generation",
     "legendFormat": "GcCountG1_Old_Generation_{{instance}}"
    }
   ]
  },
  {
   "title": "GC  Cost",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_GcTimeMillis", "legendFormat": "GcTimeMillis_{{instance}}" },
    {
     "expr": "Hadoop_HBase_GcTimeMillisG1_Young_Generation",
     "legendFormat": "GcTimeMillisG1_Young_Generation_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_GcTimeMillisG1_Old_Generation",
     "legendFormat": "GcTimeMillisG1_Old_Generation_{{instance}}"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_PauseTimeWithGc_max",
     "legendFormat": "PauseTimeWithGc_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_PauseTimeWithGc_mean",
     "legendFormat": "PauseTimeWithGc_mean_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_PauseTimeWithoutGc_max",
     "legendFormat": "PauseTimeWithoutGc_max_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_PauseTimeWithoutGc_mean",
     "legendFormat": "PauseTimeWithoutGc_mean_{{instance}}"
    }
   ]
  },
  {
   "title": "GC memoryUsageAfterGc",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_committed",
     "legendFormat": "memoryUsageAfterGc_committed_{{instance}}"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_init",
     "legendFormat": "memoryUsageAfterGc_init_{{instance}}"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_max",
     "legendFormat": "memoryUsageAfterGc_max_{{instance}}"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageAfterGc_used",
     "legendFormat": "memoryUsageAfterGc_used_{{instance}}"
    }
   ]
  },
  {
   "title": "GC memoryUsageBeforeGc",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_committed",
     "legendFormat": "memoryUsageAfterGc_committed_{{instance}}"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_init",
     "legendFormat": "memoryUsageAfterGc_init_{{instance}}"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_max",
     "legendFormat": "memoryUsageAfterGc_max_{{instance}}"
    },
    {
     "expr": "java_lang_GarbageCollector_LastGcInfo_memoryUsageBeforeGc_used",
     "legendFormat": "memoryUsageAfterGc_used_{{instance}}"
    }
   ]
  },
  {
   "title": "HLOG num_ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_hlogFileCount{instance=\"$rs:8080\"}",
     "legendFormat": "hlogFileCount_{{instance}}"
    },
    {
     "expr": "Hadoop_HBase_SyncTime_num_ops{instance=\"$rs:8080\"}"
    }
   ]
  },
  {
   "title": "HLOG hlogFileSize",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "Hadoop_HBase_hlogFileSize{instance=\"$rs:8080\"}"
    }
   ]
  },
  {
   "title": "HLOG SyncTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "Hadoop_HBase_SyncTime_max", "legendFormat": "SyncTime_max_{{instance}}" },
    { "expr": "Hadoop_HBase_SyncTime_mean", "legendFormat": "SyncTime_mean_{{instance}}" }
   ]
  }
 ]
}