#!/bin/bash
script=$(readlink -f ${BASE_SOURCE:-$0})
basedir=$(cd $(dirname ${script});pwd)
cd ${basedir}
export HADOOP_HOME=$(readlink -f ${basedir}/../hadoop_all/hadoop)
export HBASE_HOME=$(readlink -f ${basedir}/../hadoop_all/hbase)
${HBASE_HOME}/bin/hbase --config ${basedir}/hbase_client_conf/ $*
