#!/bin/bash
script=$(readlink -f ${BASE_SOURCE:-$0})
basedir=$(cd $(dirname ${script});pwd)
cd ${basedir}
HBASE_DEPLOY=${basedir}/../hadoop_all/hbase
${HBASE_DEPLOY}/bin/hbase --config ${basedir}/hbase_client_conf/ $*
