#!/bin/bash
set -e -o pipefail

basedir=$(cd $(dirname $(readlink -f ${BASH_SOURCE:-$0}));pwd)
source ${basedir}/functions.sh

kafka_dir=$(cd $(readlink -f ${basedir}/../hadoop_all/kafka);pwd)
cd ${basedir}

group=${1:?"missing 'group'"};shift
brokerList=kafka_broker0:9092,kafka_broker1:9092,kafka_broker2:9092,kafka_broker3:9092,kafka_broker4:9092 
topic=${group%%.*}

[ "${topic}" = "${group}" ] && group="${group}.default"

bin=${kafka_dir}/bin/kafka-console-consumer.sh
version=$(${bin} --version)

if startsWith "${version}" 2.5.0;then
  groupOpt="--group ${group}"
else
  groupOpt="--consumer-property group.id=${group}"
fi

${bin} --bootstrap-server ${brokerList} --topic ${topic} ${groupOpt} --from-beginning
