#!/bin/bash
basedir=$(cd $(dirname $(readlink -f ${BASH_SOURCE:-$0}));pwd)
cd ${basedir}
export SPARK_CONF_DIR=${basedir}/spark_conf_client
export TERM=xterm-color
${basedir}/../hadoop_all/spark/bin/spark-sql $@
